DROP TABLE IF EXISTS ACTIVEMQ_MSGS CASCADE;
DROP TABLE IF EXISTS ACTIVEMQ_ACKS CASCADE;
DROP INDEX IF EXISTS ACTIVEMQ_MSGS_CIDX;
DROP INDEX IF EXISTS ACTIVEMQ_MSGS_MIDX;
DROP INDEX IF EXISTS ACTIVEMQ_MSGS_EIDX;
DROP INDEX IF EXISTS ACTIVEMQ_ACKS_CIDX;
CREATE TABLE ACTIVEMQ_MSGS (
    ID BIGSERIAL PRIMARY KEY,
    CONTAINER VARCHAR(250) NOT NULL,
    MSGID_PROD VARCHAR(250) NOT NULL,
    MSGID_SEQ BIGINT NOT NULL,
    EXPIRATION BIGINT NOT NULL,
    MSG BYTEA NOT NULL,  -- Alterado de BLOB para BYTEA
    PRIORITY INTEGER NOT NULL
);

-- Criar a tabela de mensagens agendadas
CREATE TABLE ACTIVEMQ_ACKS (
    CONTAINER VARCHAR(250) NOT NULL,
    SUB_DEST VARCHAR(250),
    CLIENT_ID VARCHAR(250) NOT NULL,
    SUB_NAME VARCHAR(250) NOT NULL,
    SELECTOR VARCHAR(250),
    LAST_ACKED_ID BIGINT NOT NULL,
    PRIMARY KEY (CONTAINER, CLIENT_ID, SUB_NAME)
);

-- Criar índices para melhorar a performance
CREATE INDEX ACTIVEMQ_MSGS_CIDX ON ACTIVEMQ_MSGS (CONTAINER);
CREATE INDEX ACTIVEMQ_MSGS_MIDX ON ACTIVEMQ_MSGS (MSGID_PROD, MSGID_SEQ);
CREATE INDEX ACTIVEMQ_MSGS_EIDX ON ACTIVEMQ_MSGS (EXPIRATION);
CREATE INDEX ACTIVEMQ_ACKS_CIDX ON ACTIVEMQ_ACKS (CONTAINER);